export const unitName = [
  { key: "Select Unit Name", value: "" },
  { key: "115 Fd Wksp COy EME", value: "115 Fd Wksp Coy EME" },
  { key: "HQ 10 Inf Division", value: "HQ 10 Inf Division" },
  { key: "HQ 10 Arty Bde", value: "HQ 10 Arty Bde" },
  { key: "HQ 65 Infantry Bde ", value: "HQ 65 Infantry Bde " },
  { key: "Area HQ, Ramu ", value: "Area HQ, Ramu " },
  { key: "Station HQ, Ramu ", value: "Station HQ, Ramu " },
  { key: "Mujib Regt Arty ", value: "Mujib Regt Arty " },
  { key: " 12 Fd Regt Arty", value: "12 Fd Regt Arty " },
  { key: "9 Fd Regt Arty ", value: "9 Fd Regt Arty " },
  { key: " 47 Morter Regt Arty", value: "47 Morter Regt Arty " },
  { key: "29 Div Locating ", value: "29 Div Locating " },
  { key: "36 E Bengal ", value: "36 E Bengal " },
  { key: "26 E Bengal ", value: "26 E Bengal " },
  { key: " 16 BIR", value: "16 BIR " },
  { key: "7 Signal BN ", value: "7 Signal BN " },
  { key: " Static Signal, Ramu", value: "Static Signal, Ramu " },
  { key: "SSD, Ramu ", value: "SSD, Ramu " },
  { key: "ASU, Ramu ", value: "ASU, Ramu " },
  { key: "DGFI, Ramu ", value: "DGFI, Ramu " },
  { key: "DGSS, Ramu ", value: "DGSS, Ramu " },
  { key: "17 ECB ", value: "17 ECB " },
  { key: "28 Medium Regt Arty ", value: "28 Medium Regt Arty " },
];

export const garisionName = [
  { key: "Select Garision Name", value: "" },
  { key: "Ramu Cantonment", value: "Ramu Cantonment" },
  { key: "Savar Cantonment", value: "Savar Cantonment" },
  { key: "Chittagong Cantonment", value: "Chittagong Cantonment" },
  { key: "Bogora Cantonment", value: "Bogora Cantonment" },
  { key: "Jessore Cantonment", value: "Jessore Cantonment" },
  { key: "Comilla Cantonment", value: "Comilla Cantonment" },
];
